### ISSUE TITLE
Compatible with Dart 2.12

### ISSUE THREAD

**Issue by hyiso** [mvitlov/east_asian_width#1]
This package now only supports Dart SDK >= 2.17.0, could this package lower its Dart SDK constraints to 2.12?

I've see that only `enum EastAsianWidth` use **enum constructor** which is brought in Dart 2.17

**Comment by hyiso** [comment]
I've create a PR to solve this

**Comment by mvitlov** [comment]
Thanks @hyiso! I will update the package in a bit. 🙌
